import '../models/mentor.dart';

/// Predefined mock mentors across all 15 course categories
final List<Mentor> kMockMentors = [
  const Mentor(
    id: 'mock-math-1',
    name: 'Dr. Sokha Chea',
    subject: 'Math',
    experience: '8 years experience',
    timeSlot: 'Mon, Wed, Fri',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&fit=crop&q=80',
    rating: 4.9,
    students: 230,
    classes: 85,
    followers: 410,
    bookingPrice: 25.0,
    bio: 'Senior Mathematics lecturer specializing in Advanced Calculus, Algebra, and Bac II National Exam preparation.',
    courses: [
      Course(
        id: 101,
        tutorId: 'mock-math-1',
        title: 'Master Math Formulas & Bac II Prep',
        description: 'Complete high-yield formula breakdown and exam drills for Bac II students.',
        rating: 4.9,
        durationHours: 15,
        isFavorited: true,
        isLive: false,
        cardColor: 'orange',
        category: 'Math',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-physic-1',
    name: 'Prof. Chantha Vong',
    subject: 'Physic',
    experience: '7 years experience',
    timeSlot: 'Tue, Thu, Sat',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&fit=crop&q=80',
    rating: 4.8,
    students: 175,
    classes: 60,
    followers: 320,
    bookingPrice: 22.0,
    bio: 'Dedicated physics instructor focusing on classical mechanics, electromagnetism, and hands-on problem solving.',
    courses: [
      Course(
        id: 102,
        tutorId: 'mock-physic-1',
        title: 'High School Physics Core Concepts',
        description: 'Master physics fundamentals, thermodynamics, and optics with step-by-step guidance.',
        rating: 4.8,
        durationHours: 12,
        isFavorited: false,
        isLive: true,
        cardColor: 'purple',
        category: 'Physic',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-khmer-1',
    name: 'Ms. Srey Pich Rath',
    subject: 'Khmer',
    experience: '6 years experience',
    timeSlot: 'Mon, Tue, Thu',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&fit=crop&q=80',
    rating: 4.9,
    students: 190,
    classes: 70,
    followers: 360,
    bookingPrice: 18.0,
    bio: 'Passionate Khmer language and literature educator helping students excel in essay writing, grammar, and reading comprehension.',
    courses: [
      Course(
        id: 103,
        tutorId: 'mock-khmer-1',
        title: 'Khmer Essay Writing & Literature Masterclass',
        description: 'Sharpen your literary analysis, poetic appreciation, and formal essay composition skills.',
        rating: 4.9,
        durationHours: 10,
        isFavorited: true,
        isLive: false,
        cardColor: 'amber',
        category: 'Khmer',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-english-1',
    name: 'Michael Harrison',
    subject: 'English',
    experience: '10 years experience',
    timeSlot: 'Daily',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&fit=crop&q=80',
    rating: 5.0,
    students: 340,
    classes: 120,
    followers: 650,
    bookingPrice: 30.0,
    bio: 'Native English speaker & certified IELTS trainer. Guided hundreds of students to achieve 7.5+ in IELTS Speaking & Writing.',
    courses: [
      Course(
        id: 104,
        tutorId: 'mock-english-1',
        title: 'IELTS Band 7.5+ Speaking & Writing Strategy',
        description: 'Targeted drills, mock speaking interviews, and essay review to ace the official IELTS examination.',
        rating: 5.0,
        durationHours: 18,
        isFavorited: true,
        isLive: true,
        cardColor: 'red',
        category: 'English',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-chinese-1',
    name: 'Li Wei (李伟)',
    subject: 'Chinese',
    experience: '5 years experience',
    timeSlot: 'Wed, Fri, Sun',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&fit=crop&q=80',
    rating: 4.9,
    students: 160,
    classes: 55,
    followers: 290,
    bookingPrice: 28.0,
    bio: 'HSK Level 6 accredited teacher. Specialized in conversational Mandarin and Business Chinese for professionals.',
    courses: [
      Course(
        id: 105,
        tutorId: 'mock-chinese-1',
        title: 'Business Mandarin & HSK 4-5 Accelerator',
        description: 'Practical conversations, workplace vocabulary, and HSK test strategies tailored to fast progress.',
        rating: 4.9,
        durationHours: 14,
        isFavorited: false,
        isLive: false,
        cardColor: 'crimson',
        category: 'Chinese',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-spanish-1',
    name: 'Sofia Martinez',
    subject: 'Spanish',
    experience: '6 years experience',
    timeSlot: 'Tue, Thu, Sat',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&fit=crop&q=80',
    rating: 4.8,
    students: 110,
    classes: 45,
    followers: 230,
    bookingPrice: 25.0,
    bio: 'Native Spanish educator from Madrid. Learn authentic pronunciation, grammar, and Latin culture in interactive sessions.',
    courses: [
      Course(
        id: 106,
        tutorId: 'mock-spanish-1',
        title: 'Conversational Spanish for Beginners & Travelers',
        description: 'Immersive Spanish language course covering daily dialogue, travel phrases, and essential grammar.',
        rating: 4.8,
        durationHours: 12,
        isFavorited: false,
        isLive: false,
        cardColor: 'amber',
        category: 'Spanish',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-primary-1',
    name: 'Teacher Navy Meng',
    subject: 'Primary School',
    experience: '9 years experience',
    timeSlot: 'Mon - Fri',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&fit=crop&q=80',
    rating: 4.9,
    students: 260,
    classes: 95,
    followers: 480,
    bookingPrice: 15.0,
    bio: 'Early childhood and primary education specialist focusing on foundation literacy, fun arithmetic, and critical thinking.',
    courses: [
      Course(
        id: 107,
        tutorId: 'mock-primary-1',
        title: 'Primary Foundation Math & Creative Reading',
        description: 'Gamified learning program designed to boost young learners confidence and academic results.',
        rating: 4.9,
        durationHours: 16,
        isFavorited: true,
        isLive: true,
        cardColor: 'blue',
        category: 'Primary School',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-highschool-1',
    name: 'Mr. Bunreach Keo',
    subject: 'High School',
    experience: '8 years experience',
    timeSlot: 'Weekends',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&fit=crop&q=80',
    rating: 4.8,
    students: 215,
    classes: 80,
    followers: 390,
    bookingPrice: 22.0,
    bio: 'Experienced high school mentor preparing grade 10-12 students across STEM subjects for high academic achievement.',
    courses: [
      Course(
        id: 108,
        tutorId: 'mock-highschool-1',
        title: 'High School National Exam Bootcamp',
        description: 'Comprehensive review across science and math subjects with past national examination papers.',
        rating: 4.8,
        durationHours: 20,
        isFavorited: false,
        isLive: false,
        cardColor: 'blue',
        category: 'High School',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-gym-1',
    name: 'Coach Rithy Sam',
    subject: 'Gym Trainer',
    experience: '7 years experience',
    timeSlot: 'Morning & Evening',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&fit=crop&q=80',
    rating: 5.0,
    students: 140,
    classes: 65,
    followers: 420,
    bookingPrice: 35.0,
    bio: 'Certified strength and conditioning coach helping clients transform their body composition, strength, and posture.',
    courses: [
      Course(
        id: 109,
        tutorId: 'mock-gym-1',
        title: 'Full Body Strength & Hypertrophy Program',
        description: 'Structured progressive overload training and customized nutrition guidance for peak fitness.',
        rating: 5.0,
        durationHours: 8,
        isFavorited: true,
        isLive: false,
        cardColor: 'slate',
        category: 'Gym Trainer',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-volleyball-1',
    name: 'Coach Dara Heng',
    subject: 'Volleyball Coach',
    experience: '6 years experience',
    timeSlot: 'Sat & Sun',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&fit=crop&q=80',
    rating: 4.8,
    students: 90,
    classes: 40,
    followers: 210,
    bookingPrice: 30.0,
    bio: 'Former national athlete and passionate volleyball coach. Specializing in serving precision, spike mechanics, and defensive footwork.',
    courses: [
      Course(
        id: 110,
        tutorId: 'mock-volleyball-1',
        title: 'Volleyball Spike & Jump Serve Mastery',
        description: 'Biomechanical breakdown of explosive vertical jumping and powerful spike placement.',
        rating: 4.8,
        durationHours: 10,
        isFavorited: false,
        isLive: false,
        cardColor: 'blue',
        category: 'Volleyball Coach',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-football-1',
    name: 'Coach David Prom',
    subject: 'Football Coach',
    experience: '10 years experience',
    timeSlot: 'Tue, Thu, Sat',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&fit=crop&q=80',
    rating: 4.9,
    students: 240,
    classes: 90,
    followers: 510,
    bookingPrice: 35.0,
    bio: 'UEFA B certified youth football coach. Teaching modern tactical awareness, close ball control, and match fitness.',
    courses: [
      Course(
        id: 111,
        tutorId: 'mock-football-1',
        title: 'Modern Football Dribbling & Game Tactics',
        description: 'Elite drills on agility, 1v1 attacking, vision, and team tactical positioning.',
        rating: 4.9,
        durationHours: 14,
        isFavorited: true,
        isLive: false,
        cardColor: 'green',
        category: 'Football Coach',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-swimming-1',
    name: 'Coach Pisey Ouk',
    subject: 'Swimming Coach',
    experience: '5 years experience',
    timeSlot: 'Mon, Wed, Sat',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&fit=crop&q=80',
    rating: 4.9,
    students: 120,
    classes: 50,
    followers: 270,
    bookingPrice: 28.0,
    bio: 'Certified lifeguard and competitive swim trainer. Guiding both nervous beginners and competitive stroke swimmers.',
    courses: [
      Course(
        id: 112,
        tutorId: 'mock-swimming-1',
        title: 'Freestyle Technique & Water Confidence',
        description: 'Step-by-step breathing control, streamlined body positioning, and efficient stroke mechanics.',
        rating: 4.9,
        durationHours: 10,
        isFavorited: false,
        isLive: false,
        cardColor: 'cyan',
        category: 'Swimming Coach',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-driving-1',
    name: 'Instructor Vibol Chhorn',
    subject: 'Teach Driving',
    experience: '12 years experience',
    timeSlot: 'Daily Flexible',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&fit=crop&q=80',
    rating: 4.7,
    students: 310,
    classes: 110,
    followers: 460,
    bookingPrice: 20.0,
    bio: 'Patient and certified driving instructor. Over a decade of helping new drivers pass test on their first attempt with defensive skills.',
    courses: [
      Course(
        id: 113,
        tutorId: 'mock-driving-1',
        title: 'Road Test Prep & Defensive City Driving',
        description: 'Parallel parking, highway merging, road hazard reaction, and official exam criteria review.',
        rating: 4.7,
        durationHours: 12,
        isFavorited: false,
        isLive: false,
        cardColor: 'slate',
        category: 'Teach Driving',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-badminton-1',
    name: 'Coach Kiri Tep',
    subject: 'Badminton Coach',
    experience: '7 years experience',
    timeSlot: 'Tue, Fri, Sun',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&fit=crop&q=80',
    rating: 4.8,
    students: 150,
    classes: 60,
    followers: 330,
    bookingPrice: 25.0,
    bio: 'Former club tournament champion. Specializing in rapid footwork, smash mechanics, backhand recovery, and doubles strategy.',
    courses: [
      Course(
        id: 114,
        tutorId: 'mock-badminton-1',
        title: 'Badminton Footwork, Smash & Match Strategy',
        description: 'Master court coverage, deceptive drop shots, and explosive smashes through structured practice.',
        rating: 4.8,
        durationHours: 12,
        isFavorited: true,
        isLive: false,
        cardColor: 'green',
        category: 'Badminton Coach',
      ),
    ],
  ),
  const Mentor(
    id: 'mock-general-1',
    name: 'Ms. Gooooo',
    subject: 'General',
    experience: '5 years experience',
    timeSlot: 'Flexible',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&fit=crop&q=80',
    rating: 5.0,
    students: 120,
    classes: 50,
    followers: 300,
    bookingPrice: 20.0,
    bio: 'Versatile academic and life skills mentor providing structured guidance and personalized study techniques.',
    courses: [
      Course(
        id: 115,
        tutorId: 'mock-general-1',
        title: 'General Learning & Essential Study Skills',
        description: 'Effective note-taking, memory retention systems, and time management for academic excellence.',
        rating: 5.0,
        durationHours: 8,
        isFavorited: false,
        isLive: false,
        cardColor: 'blue',
        category: 'General',
      ),
    ],
  ),
];

/// Helper to get all mock courses formatted as map
/// so they are 100% compatible with existing course listing logic.
List<Map<String, dynamic>> getMockCoursesAsJson() {
  final List<Map<String, dynamic>> list = [];
  for (final m in kMockMentors) {
    for (final c in m.courses) {
      list.add({
        'id': c.id,
        'title': c.title,
        'description': c.description,
        'category': c.category,
        'subject': c.category,
        'rating': c.rating,
        'duration_hours': c.durationHours,
        'card_color': c.cardColor,
        'is_featured': true,
        'Users': {'name': m.name},
        'instructorName': m.name,
      });
    }
  }
  return list;
}

/// Look up a mock mentor by ID
Mentor? getMockMentorById(String id) {
  for (final m in kMockMentors) {
    if (m.id == id) return m;
  }
  return null;
}

/// Filter mock mentors by subject/category
List<Mentor> getMockMentorsForSubject(String subject) {
  final sub = subject.toLowerCase().trim();
  return kMockMentors.where((m) {
    final mSub = m.subject.toLowerCase().trim();
    return mSub.contains(sub) || sub.contains(mSub);
  }).toList();
}
